# config.yaml

# --------------------------------------------------
# List of modes
# --------------------------------------------------
# MODE_NO_MODE                        = 0x00,
# MODE_PROFILE_POSITION               = 0x01,
# MODE_PROFILE_VELOCITY               = 0x03,
# MODE_PROFILE_TORQUE                 = 0x04,
# MODE_HOMING                         = 0x06,
# MODE_INTERPOLATION_POSITION         = 0x07,
# MODE_CYCLIC_SYNCHRONOUS_POSITION    = 0x08,
# MODE_CYCLIC_SYNCHRONOUS_VELOCITY    = 0x09,
# MODE_CYCLIC_SYNCHRONOUS_TORQUE      = 0x0A,
# MODE_PROFILE_COMMUTATION            = 0x0F

actuators:
  - name: joint_1
    mode: 8
    target_torque: 200
    target_velocity: 50000
    target_position: -1500000

#  - name: joint_2
#    mode: 9
#    target_torque: 200
#    target_velocity: 500000
#    target_position: 0



backlash_test:
  torque_mag: 15        # torque_mag / 1000 * rated torque
  flip_dt_ms: 10        # flip ms
  period_us: 5000        # control loop = 0.5 ms
  backlash_threshold: 40 # if backlash exceeds this number, terminate

backlash_sweep:
  N: 12                   # number of positions
  position_error_threshold: 1000   # counts
  position_error_timeout_ms: 40000 # timeout in ms
  position_zero_error_timeout_ms: 100000 # timeout to zero pos in ms
  measure_time_s: 2       # seconds per position
  csv_path: "../output/backlash_results-test.csv"   # optional; default "backlash_results.csv"

