# config.yaml

# --------------------------------------------------
# List of modes
# --------------------------------------------------
# MODE_NO_MODE                        = 0x00,
# MODE_PROFILE_POSITION               = 0x01,
# MODE_PROFILE_VELOCITY               = 0x03,
# MODE_PROFILE_TORQUE                 = 0x04,
# MODE_HOMING                         = 0x06,
# MODE_INTERPOLATION_POSITION         = 0x07,
# MODE_CYCLIC_SYNCHRONOUS_POSITION    = 0x08,
# MODE_CYCLIC_SYNCHRONOUS_VELOCITY    = 0x09,
# MODE_CYCLIC_SYNCHRONOUS_TORQUE      = 0x0A,
# MODE_PROFILE_COMMUTATION            = 0x0F

actuators:
  - name: joint_1
    mode: 10
    target_torque: 200
    target_velocity: 1000000
    target_position: 0

#  - name: joint_2
#    mode: 9
#    target_torque: 200
#    target_velocity: 500000
#    target_position: 0



# backlash_test:
#   torque_mag: 10        # torque_mag / 1000 * rated torque
#   flip_dt_ms: 15        # flip ms
#   period_us: 500        # control loop = 5 ms
#   backlash_threshold: 80 # if backlash exceeds this number, terminate
#   backlash_outlier_threshold: 200 # if backlash exceeds this number, regard it as outlier

# backlash_sweep:
#   N: 12                   # number of positions
#   position_error_threshold: 1000   # counts
#   position_error_timeout_ms: 40000 # timeout in ms
#   position_zero_error_timeout_ms: 200000 # timeout to zero pos in ms
#   measure_time_s: 2       # seconds per position
#   csv_path: "../output/backlash-friction-test.csv"   # optional; default "backlash_results.csv"

# friction_test:
#   moving_threshold: 1000
#   torque_step: 5
#   dwell_ms: 100
#   torque_limit:  1000
#   period_us: 500            # optional; match your loop
#   position_error_threshold: 1000
#   position_error_timeout_ms: 40000

